### PR TITLE
stop Npc animation if player wants to talk

### PR DESCRIPTION
**Pull request by thokkat**
For long duration animations like the sword training.

fixes https://github.com/Try/OpenGothic/issues/296

### CODE REVIEW

**Comment by Try** [comment]
Hi, @thokkat !

This solution doesn't seems to be complete. The `1H_FREE` and other transition animations are problematic not only for dialogs:
изображение

I'm not sure what is correct behavior here. Maybe hookup on ai_clearqueue instead

**Comment by thokkat** [comment]
Are there cases where an animation isn't allowed to be interrupted? Otherwise something like this:
```
    case AI_PlayAnim:{
      if(auto sq =playAnimByName(act.s0.c_str(),BS_NONE)) {
      // implAniWait(uint64_t(sq->totalTime()));
        } else {
```

**Comment by Try** [comment]
> Are there cases where an animation isn't allowed to be interrupted?

Intimidation animations for monsters - to make sure work will not run forward, while barking

**Comment by thokkat** [comment]
Close because proper solution for all cases needs to be figured out.

**Pull request closed without merging**
