### PR TITLE
Added arm64 as supported architecture for edd-dbg

### PR DESCRIPTION
**Pull request by pawcijo**
Fix for macos build, not sure if this is the right place for PR :)

### CODE REVIEW

**Comment by Try** [comment]
Hi, @pawcijo !

> added arm64 as supported architecture

Can you clarify this statement? Arm64 for mac been supported for a while, with no build issues.  Or do you mean crash-logger support?

**Comment by pawcijo** [comment]
When i try to build the project on m1 macbook  i get  "unsupported architecture :(", if frames.cpp is from crash-logger than yes your right :)

**Comment by Try** [comment]
How do you build opengothic on mac? `edd` library is enabled only on windows targets

**Comment by pawcijo** [comment]
The same as it goes in Readme :
`cmake -H. -Bbuild -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
cmake --build ./build --target Gothic2Notr`

**Comment by Try** [comment]
Hm, something is not quite right here. Can you please provide build log, cmake version, and more details overall?

In build script there is:
```
add_subdirectory(lib/edd-dbg)
include_directories(lib/edd-dbg/include)
if(WIN32)
  target_link_libraries(${PROJECT_NAME} edd_dbg)
endif()
```
Maybe `add_subdirectory` behaves different across different versions.

**Comment by pawcijo** [comment]
Cannot reproduce anymore, it might benn some wild cmake error on macos

**Pull request closed without merging**
