### PR TITLE
Update playercontrol.cpp

### PR DESCRIPTION
**Pull request by Schlumpf7**
Outsourcing Gamepad

### CODE REVIEW

**Comment by Try** [comment]
Hi, @Schlumpf7 and thanks for PR!

Unfortunately, this cannot be merged into upstream. Generally in project I'm very conservative on third-party libraries following white-list approach essentially. Linking SDL/SDL2 in particular is definitely not acceptable, due to low quality of the library.

**Comment by Schlumpf7** [comment]
What about libgamepad for controller integration?

**Comment by Try** [comment]
As touched in https://github.com/Try/OpenGothic/issues/287, current direction is to take a native api and built on top.
For windows: https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/input/overviews/input-readings
For apple: https://developer.apple.com/documentation/gamecontroller/handling_input_events?language=objc

libgamepad can be used as test-reference/inspiration for api.

**Comment by Nindaleth** [comment]
@Try do you have any preference for Linux as well? Here's an archwiki page on it: [Gamepad](https://wiki.archlinux.org/title/Gamepad)

**Comment by niklaskorz** [comment]
> Linking SDL/SDL2 in particular is definitely not acceptable, due to low quality of the library.

That's a very bold/rude statement that in my experience does not hold. Care to elaborate with sources, not unfounded opinions?
SDL has Valve's backing nowadays and even has become their go-to recommendation for any cross platform input handling. I don't think it's realistic or wise to attempt supporting gamepad input on Linux without it.

Edit: I recommend reading <https://blogs.gnome.org/alicem/2024/10/24/steam-deck-hid-and-libmanette-adventures/> to understand why trying to do everything from scratch using evdev et al is probably a bad idea. The Gnome project's [libmanette](https://gnome.pages.gitlab.gnome.org/libmanette/) is another implementation that supports SDL's widely established control mapping format.

**Pull request closed without merging**
